---
name: bag-courier
services:
  dark-blue-dev:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - ./config/config.yml:/app/config/config.yml
      - ./.ssh/:/app/.ssh/:ro
    command: ["ruby", "run_dark_blue.rb"]
  dark-blue-prod:
    build:
      context: .
      target: production
    volumes:
      - ./config/config.yml:/app/config/config.yml
