---
name: bag-courier
services:
  dark-blue-dev:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
     - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    command: ["ruby", "run_dark_blue.rb"]
  dark-blue-prod:
    build:
      context: .
      target: production
    volumes:
      - ./config/config.yml:/app/config/config.yml
