# Bag Courier Config Example/Template

# Settings
# One of info, debug, error, warn, trace, fatal
LogLevel: "info"
WorkingDir: "./prep"
ExportDir: "./export"
# Determines whether the process skips sending bag(s)
DryRun: false
# Limit for the size of objects to be processed (optional)
# This is useful for development or in environments where larger files cannot be processed.
ObjectSizeLimit: 2000000000

# Database (optional)
# Values provided should work for local development with Docker
# While technically optional, it is required when running all tests.
Database:
  Host: database
  Database: dpact_pres_service
  Port: 3306
  User: dpact_user
  Password: dpact_pw

DarkBlue:
  ArchivematicaInstances:
      # Name is used for the context in the bag identifier
    - Name:
      # RepositoryName is used to create a Repository database record
      RepositoryName:
      API:
        Username:
        APIKey:
        BaseURL:
        LocationUUID:
      Remote:
        Type: file_system
        Settings:
          FileSystemRemotePath:
        # Type: sftp
        # Settings:
        #   User:
        #   Host:
        #   KeyPath:

# Repository
Repository:
RepositoryDescription:

# Remote(s)
TargetRemote:
  Type: aptrust
  Settings:
    # APTrust AWS remote settings
    ReceivingBucket:
    RestoreBucket:
    BucketRegion:
    AwsAccessKeyId:
    AwsSecretAccessKey:

# APTrust
APTrust:
  Username:
  APIKey:
  BaseURL:
