# Bag Courier Config Example/Template

# Determines whether the process skips sending bag(s)
DryRun: false
WorkingDir: "./prep"
ExportDir: "./export"
TestSourceDir: "./test_source/work_dir"

Repository:
RepositoryDescription:

# Either aptrust or file_system
RemoteType:

# APTrust AWS remote settings
ReceivingBucket:
RestoreBucket:
BucketRegion:
AwsAccessKeyId:
AwsSecretAccessKey:

# File System remote settings
FileSystemRemotePath:
