# Bag Courier Config Example/Template

# Settings
# One of info, debug, error, warn, trace, fatal
LogLevel: "info"
WorkingDir: "./prep"
ExportDir: "./export"
# Determines whether the process skips sending bag(s)
DryRun: false
# Objects this size or larger in bytes will not be processed.
ObjectSizeLimit: 2000000000

DarkBlue:
  ArchivematicaInstances:
    - Name:
      API:
        Username:
        APIKey:
        BaseURL:
        LocationUUID:
      Remote:
        Type: file_system
        Settings:
          FileSystemRemotePath:
        # Type: sftp
        # Settings:
        #   User:
        #   Host:
        #   KeyPath:

# Repository
Repository:
RepositoryDescription:

# Remote(s)
TargetRemote:
  RemoteType: aptrust
  RemoteSettings:
    # APTrust AWS remote settings
    ReceivingBucket:
    RestoreBucket:
    BucketRegion:
    AwsAccessKeyId:
    AwsSecretAccessKey:
