# Bag Courier Config Example/Template

# Determines whether the process skips sending bag(s)
SourceDir: "./test_source"
WorkingDir: "./prep"
ExportDir: "./export"
DryRun: false

# Archivematica REST API
ArchivematicaBaseURL:
ArchivematicaUsername:
ArchivematicaAPIKey:
LocationUUID:

Repository:
RepositoryDescription:

# Remotes
SourceRemote:
  RemoteType: file_system
  RemoteSettings:
    FileSystemRemotePath:
  # RemoteType: sftp
  # RemoteSettings:
  #   SftpUser:
  #   SftpHost:
  #   SftpKeyPath:
TargetRemote:
  RemoteType: aptrust
  RemoteSettings:
    # APTrust AWS remote settings
    ReceivingBucket:
    RestoreBucket:
    BucketRegion:
    AwsAccessKeyId:
    AwsSecretAccessKey:
