---
name: Build release

on:
  release:
    types: [ released ]

jobs:
  build-production:
    name: Build production ${{ github.event.release.tag_name }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@2012bb6a322ad02c45c01372de2f5e2e3d7329acv # 1.6.7
    with:
      image_name: bag-courier
      tag: ${{ github.event.release.tag_name }}
      dockerfile: Dockerfile
    secrets: inherit
