name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10
        env:
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: test_database
          MARIADB_ROOT_PASSWORD: password
        ports: ["3306:3306"]
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Wait for MariaDB
        run: |
          for i in {1..10}
          do
              if [[ $(mysqladmin ping -h"127.0.0.1" -P"3306" --silent) -eq 0 ]]; then
                  exit 0
              else
                  sleep 3
              fi
          done
          exit 1
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true
      - name: Run tests
        env:
          SETTINGS_LOG_LEVEL: debug
          SETTINGS_WORKING_DIR: ./prep
          SETTINGS_EXPORT_DIR: ./export
          SETTINGS_DRY_RUN: false
          SETTINGS_OBJECT_SIZE_LIMIT: 2000
          REPOSITORY_NAME: test
          REPOSITORY_DESCRIPTION: test
          ARCHIVEMATICA_DEV_NAME: test
          ARCHIVEMATICA_DEV_REPOSITORY_NAME: test
          ARCHIVEMATICA_DEV_API_USERNAME: test
          ARCHIVEMATICA_DEV_API_API_KEY: test
          ARCHIVEMATICA_DEV_API_BASE_URL: test
          ARCHIVEMATICA_DEV_API_LOCATION_UUID: test
          ARCHIVEMATICA_DEV_REMOTE_TYPE: file_system
          ARCHIVEMATICA_DEV_REMOTE_SETTINGS_USER: test
          ARCHIVEMATICA_DEV_REMOTE_SETTINGS_HOST: test
          ARCHIVEMATICA_DEV_REMOTE_SETTINGS_KEY_PATH: /test
          APTRUST_API_USERNAME: test
          APTRUST_API_API_KEY: test
          APTRUST_API_BASE_URL: test
          APTRUST_REMOTE_TYPE: aptrust
          APTRUST_REMOTE_SETTINGS_RECEIVING_BUCKET: test
          APTRUST_REMOTE_SETTINGS_RESTORE_BUCKET: test
          APTRUST_REMOTE_SETTINGS_BUCKET_REGION: test
          APTRUST_REMOTE_SETTINGS_AWS_ACCESS_KEY_ID: test
          APTRUST_REMOTE_SETTINGS_AWS_SECRET_ACCESS_KEY: test
          DATABASE_HOST: 127.0.0.1
          DATABASE_DATABASE: test_database
          DATABASE_PORT: 3306
          DATABASE_USER: user
          DATABASE_PASSWORD: password
        run: bundle exec rake test
